
# Day 0️⃣2️⃣7️⃣: Pre-LLMs II (Embeddings 🔢🔢🔢 II)

---

$$\text{"... And you shall know a word by the company it keeps."}$$
$$\text{John B. Firth}$$

---

This notebook is a small tutorial for understanding how embeddings work.

---

Steps:

1️⃣ NumPy Importation

2️⃣ Embedding Table ($E$)

3️⃣ One-hot Embedding ($X$)

4️⃣ Matrix multiplication ($X \times E$)

---

1️⃣ NumPy Importation

In [1]:
# 1️⃣ NumPy Importation
import numpy as np

In [2]:
#### ---- Experiment with this. Ensure the value is not greater than 9 and nor smaller than 0 ----
embedding_index_to_select = 0

assert -1 < embedding_index_to_select < 10, f"""Value for `embedding_index_to_select` ({embedding_index_to_select}) 
should be less than 10 and greater than -1"""

In [3]:
### ----  DO NOT CHANGE ---- ###
num_embeddings = 10
embedding_dimensions = 10

---

2️⃣ Embedding Table ($E$)

In [4]:
#2️⃣ Embedding Table ($E$)
E = np.arange(1, (num_embeddings * embedding_dimensions) + 1)

In [5]:
E = E.reshape(10, 10)

In [6]:
E

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

---

3️⃣ One-hot Embedding ($X$)

In [7]:
# 3️⃣ One-hot Embedding ($X$)
X = np.zeros(shape=(1, 10))
X[:, 3] = 1

---

4️⃣ Matrix multiplication ($X \times E$)

In [8]:
# 4️⃣ Matrix multiplication ($X \times E$)
np.matmul(X, E)

### ----  DO NOT CHANGE ---- ###

array([[31., 32., 33., 34., 35., 36., 37., 38., 39., 40.]])

---

Feel free to experiment with the code above. Change the value for the `embedding_index_to_select` variable within the provided guidelines i.e., it must be a value between 0 and 9.

Whenever you change the value for the `embedding_index_to_select` variable, run the code again! Observe the results.

---

$$Question$$
$$ \text{How does the value of the embedding\_index\_to\_select variable relate to the results observed from the matrix multiplication 🤔?} $$

---

---

Now that we have played around with the idea of an embedding, let us construct the embedding as a class object.

---

In [9]:
class Embedding:
    def __init__(self, num_embeddings, embedding_dimensions, simple_embedding_table=True):
        self.num_embeddings = num_embeddings
        self.embedding_dimensions = embedding_dimensions

        if simple_embedding_table:
            self.E = np.arange(1, (embedding_dimensions * num_embeddings) + 1).reshape(num_embeddings, embedding_dimensions)
        else:
            self.E = np.empty(shape=(num_embeddings, embedding_dimensions)).astype(float)

    def __call__(self, x):
        return np.matmul(x, self.E)

---

Let us explain the class arguments above:

1. `num_embeddings`: How many embeddings do we need to learn? In our example this would be the number of employees we have.
2. `embedding_dimensions`: How many dimensions do we want our embeddings to be?
3. `simple_embedding_table`: Do we want a simple embedding table? I recommend you leave this as `True`, since it would make it easy to see what is happening with the embedding process. However, in the real world, this value would be `False`, since embedding values in the real world would be continuous values.

---

$$ Exercise $$

Switch the value of `simple_embedding_table` from `True` to `False` and run the code below. How easy is it to understand the results?

---

In [10]:
num_embeddings = 10
embedding_dimensions = 3
embedding_index_to_select = 2
simple_embedding_table=True

#### ---- Uncomment the lines below to change the values and experiment with the code after this cell ----- ######


# num_embeddings = 10
# embedding_dimensions = 3
# embedding_index_to_select = 3

# Uncomment the line below to change to False just to test; however should be True by default.
# simple_embedding_table=False

assert -1 < embedding_index_to_select < num_embeddings, f"Value for `embedding_index_to_select` ({embedding_index_to_select}) should be less than {num_embeddings} and greater than -1"

In [11]:
embedding_layer = Embedding(
    num_embeddings = num_embeddings,
    embedding_dimensions = embedding_dimensions,
    simple_embedding_table = simple_embedding_table
)

In [12]:
embedding_layer.E

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

---

As can be seen above, we have 10 rows (i.e., 10 embeddings for our 10 employees) and 3 columns (i.e., 3 embedding dimensions for each of our employees). Next, we create the input data $X$ as a one-hot encoded vector.

---

In [13]:
X = np.zeros(shape = (1, num_embeddings))
X[:, embedding_index_to_select] = 1

In [14]:
embedding_layer(X)

array([[7., 8., 9.]])

In [15]:
X.shape

(1, 10)

In [16]:
embedding_layer.E.shape

(10, 3)

---

$$Question ❓$$

$$\text{Do we neccessarily need the one-hot encoded vectors?}$$

---

Let us answer this question 😀! First, what embedding index do we have to select?

In [17]:
embedding_index_to_select

2

---

As can be seen, we are to select the embedding at index 2. So let's do that 😀!

1️⃣ Select the embedding table (i.e., embedding_layer.E).

2️⃣ Select the appropriate row from the table using the index.

---

In [18]:
embedding_table = embedding_layer.E

In [19]:
embedding_table[embedding_index_to_select]

array([7, 8, 9])

In [20]:
X = np.zeros(shape = (1, num_embeddings))
X[:, embedding_index_to_select] = 1

In [21]:
embedding_layer(X)

array([[7., 8., 9.]])

---

Do we see this 😀?! Let us try it again with an index of 5!

---

In [22]:
embedding_index_to_select = 5

In [23]:
embedding_table[embedding_index_to_select]

array([16, 17, 18])

In [24]:
X = np.zeros(shape = (1, num_embeddings))
X[:, embedding_index_to_select] = 1

In [25]:
embedding_layer(X)

array([[16., 17., 18.]])

---

$$\text{\#1. As we can see, no matter how we change the index, as long as the index is appropriate, we get the same answer.}$$

$$\text{\#2. Using the index to select the embeding directly from the table is the same thing as matrix multiplication of the one-hot vector and the embedding table!}$$

---

Now that we know how to create embedding layers, all that is left is to train the embedding model.